# Generated by Django 2.2.3 on 2020-05-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='product_name',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Product'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='p_category',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Категория'),
        ),
    ]
