# Generated by Django 2.2.3 on 2020-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('notebook', 'notebook'), ('monitor', 'monitor'), ('headphones', 'headphones'), ('storage', 'storage'), ('controller', 'controller'), ('webcam', 'webcam'), ('videocard', 'videocard'), ('paper', 'paper'), ('tv_acces', 'tv_acces'), ('note_acces', 'note_acces')], default='', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../static/css/images'),
        ),
    ]
