# Generated by Django 2.2.3 on 2020-05-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0002_auto_20200517_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='product_name',
        ),
    ]
