# Generated by Django 2.2.3 on 2020-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0002_auto_20200528_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\Programming\\my_app\\django_site\\media'),
        ),
    ]
