# Generated by Django 2.2.3 on 2020-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0003_remove_product_category_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='product_category',
            name='p_category',
            field=models.CharField(blank=True, choices=[('note', 'notebook'), ('mon', 'monitor'), ('access', 'accessories')], max_length=40, null=True, verbose_name='Категория'),
        ),
    ]
