# Generated by Django 2.2.3 on 2020-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0003_auto_20200528_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
