# Generated by Django 2.2.3 on 2020-05-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0004_auto_20200517_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Product'),
        ),
    ]
