# Generated by Django 3.0.5 on 2020-04-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0004_auto_20200427_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('notebook', 'notebook'), ('monitor', 'monitor'), ('accessories', 'accessories')], max_length=25),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(blank=True, max_length=20, null=True)),
                ('memory', models.CharField(blank=True, max_length=20, null=True)),
                ('hdd', models.CharField(blank=True, max_length=20, null=True)),
                ('videocard', models.CharField(blank=True, max_length=20, null=True)),
                ('screen', models.CharField(blank=True, max_length=20, null=True)),
                ('op_system', models.CharField(blank=True, max_length=20, null=True)),
                ('connector', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('diagonal', models.CharField(blank=True, max_length=20, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Product', verbose_name='Название товара')),
            ],
        ),
    ]
