# Generated by Django 3.0.5 on 2020-04-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0005_auto_20200428_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='product',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='descrip',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Description', verbose_name='Описание'),
        ),
    ]
