# Generated by Django 3.0.5 on 2020-04-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0006_auto_20200428_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Характеристики'},
        ),
    ]
