# Generated by Django 2.2.3 on 2020-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0007_remove_product_category_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
