# Generated by Django 3.0.5 on 2020-04-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0007_auto_20200428_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Характеристики', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, choices=[('china', 'China'), ('japan', 'Japan'), ('taiwan', 'Taiwan'), ('korea', 'Korea'), ('usa', 'USA')], max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descrip',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Description', verbose_name='Описание'),
        ),
    ]
