# Generated by Django 3.0.5 on 2020-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0008_auto_20200428_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='op_system',
            new_name='os',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('note', 'notebook'), ('monitor', 'monitor'), ('accessories', 'accessories')], max_length=25),
        ),
    ]
