# Generated by Django 3.0.5 on 2020-04-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0009_auto_20200428_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='product_name',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Product'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, choices=[('china', 'China'), ('japan', 'Japan'), ('taiwan', 'Taiwan'), ('korea', 'Korea'), ('usa', 'Usa')], max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('note', 'notebook'), ('mon', 'monitor'), ('access', 'accessories')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='descrip',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
