# Generated by Django 2.2.3 on 2020-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0009_auto_20200517_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='p_category',
            field=models.IntegerField(choices=[('note', 'note'), ('mon', 'mon'), ('access', 'accessories')], max_length=40, null=True, verbose_name='Категория'),
        ),
    ]
