# Generated by Django 3.0.5 on 2020-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0010_auto_20200429_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='processor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
