# Generated by Django 3.0.5 on 2020-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0011_auto_20200429_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='connector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='os',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='screen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
