# Generated by Django 2.2.3 on 2020-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0022_auto_20200518_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='p_category',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Категория'),
        ),
    ]
