# Generated by Django 2.2.3 on 2020-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0024_auto_20200518_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('notebook', 'notebook'), ('monitor', 'monitor'), ('access', 'accessories')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='p_category',
            field=models.CharField(blank=True, choices=[('notebook', 'notebook'), ('monitor', 'monitor'), ('access', 'accessories')], max_length=40, null=True, verbose_name='Категория'),
        ),
    ]
