# Generated by Django 2.2.3 on 2020-05-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0025_auto_20200518_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_category',
        ),
    ]
