# Generated by Django 2.2.3 on 2020-05-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0026_delete_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('notebook', 'notebook'), ('monitor', 'monitor')], default='', max_length=50),
        ),
    ]
