# Generated by Django 2.2.3 on 2020-05-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0027_auto_20200518_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('notebook', 'notebook'), ('monitor', 'monitor')], default='', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descrip',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Description', verbose_name='Характеристики товара'),
        ),
    ]
